"""init migration

Revision ID: 456259e8f141
Revises: 
Create Date: 2025-10-09 00:24:40.808183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '456259e8f141'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colaboradores',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NOME', sa.String(), nullable=False),
    sa.Column('CPF', sa.String(), nullable=False),
    sa.Column('TELEFONE', sa.String(), nullable=False),
    sa.Column('CARGO', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('CPF')
    )
    op.create_table('remedios',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NOME', sa.String(), nullable=False),
    sa.Column('DESCRICAO', sa.String(), nullable=False),
    sa.Column('PRECO', sa.Float(), nullable=False),
    sa.Column('ESTOQUE', sa.Integer(), nullable=False),
    sa.Column('RECEITA', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('usuarios',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NOME', sa.String(), nullable=False),
    sa.Column('EMAIL', sa.String(), nullable=False),
    sa.Column('SENHA', sa.String(), nullable=False),
    sa.Column('ATIVO', sa.Boolean(), nullable=True),
    sa.Column('ADMIN', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('EMAIL')
    )
    op.create_table('clientes',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NOME', sa.Integer(), nullable=False),
    sa.Column('ENDERECO', sa.String(), nullable=False),
    sa.Column('CPF', sa.String(), nullable=False),
    sa.Column('TELEFONE', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['NOME'], ['usuarios.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('CPF')
    )
    op.create_table('pets',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NOME', sa.String(), nullable=False),
    sa.Column('ESPECIE', sa.String(), nullable=False),
    sa.Column('RACA', sa.String(), nullable=False),
    sa.Column('ENDERECO_DONO', sa.String(), nullable=False),
    sa.Column('CLIENTE_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CLIENTE_ID'], ['clientes.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    op.drop_table('clientes')
    op.drop_table('usuarios')
    op.drop_table('remedios')
    op.drop_table('colaboradores')
    # ### end Alembic commands ###
