"""criação de novas colunas para endereço em usuários

Revision ID: f6b7ffcc01d1
Revises: 456259e8f141
Create Date: 2025-10-14 16:32:07.186414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6b7ffcc01d1'
down_revision: Union[str, Sequence[str], None] = '456259e8f141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remover constraints não é suportado no SQLite, então apenas remova a coluna ENDERECO
    with op.batch_alter_table('clientes') as batch_op:
        batch_op.drop_column('ENDERECO')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes') as batch_op:
        batch_op.add_column(sa.Column('ENDERECO', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
